system:
  name: "Quant Trading System"
  version: "2.5.0"
  environment: "development"
  debug: true
  log_level: "INFO"

quantum:
  enabled: true
  consciousness_mode: "advanced"
  dimensional_analysis: 11
  sacred_geometry_validation: true
  cosmic_alignment_threshold: 0.6
  zero_point_sensitivity: 0.88
  angelic_connection_level: "open"
  divine_channel_active: true
  modules:
    alien_decoder:
      sensitivity: 0.85
      pattern_depth: 7
    cosmic_channeler:
      alignment_threshold: 0.9
      cosmic_frequency: 432
    zero_point:
      detection_threshold: 0.92
      field_sensitivity: 0.88
    angel_decoder:
      consciousness_level: "high"
      divine_channel: "open"

trading:
  mode: "paper"
  balance: 100000.0
  currency: "USD"
  timezone: "UTC"
  hours_start: "09:30"
  hours_end: "16:00"
  max_position_size: 0.1
  risk_tolerance: 0.02
  stop_loss_percentage: 0.02
  take_profit_percentage: 0.05
  never_loss_protection: true
  protection_layers: 9
  accuracy_multiplier: 2.5
  max_daily_loss: 50000
  risk_management:
    enabled: true
    max_leverage: 10
    stop_loss_percentage: 0.02
    take_profit_percentage: 0.05

never_loss_protection:
  enabled: true
  layers: 9
  max_daily_loss: 50000
  max_position_size: 0.1
  risk_tolerance: 0.02
  stop_loss_percentage: 0.02
  take_profit_percentage: 0.05

database:
  url: "postgresql://qts:password@localhost:5432/qts"
  pool_size: 20
  max_overflow: 30
  echo: false
  timeout: 30

redis:
  url: "redis://localhost:6379/0"
  password: ""
  db: 0
  max_connections: 20

celery:
  broker_url: "redis://localhost:6379/1"
  result_backend: "redis://localhost:6379/2"
  task_serializer: "json"
  result_serializer: "json"

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: true
  log_level: "info"
  cors_origins: ["*"]

dashboard:
  host: "0.0.0.0"
  port: 8501
  theme: "dark"

data:
  sources:
    - yfinance
    - websocket
    - prometheus
  cache_enabled: true
  cache_duration: 3600

monitoring:
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
    admin_password: "admin"
  mlflow:
    enabled: true
    port: 5000
    tracking_uri: "http://localhost:5000"
    experiment_name: "quant-trading-system"
    artifact_root: "./mlruns"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/qts.log"
  max_bytes: 10485760
  backup_count: 5
  max_size: "10MB"

security:
  secret_key: "your_secret_key_here_change_in_production"
  jwt_secret_key: "your_jwt_secret_key_here"
  jwt_algorithm: "HS256"
  jwt_expiration_hours: 24
  encryption_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8501"

notifications:
  discord_webhook_url: ""
  slack_webhook_url: ""
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from_address: "noreply@quanttradingsystem.com"
    smtp_host: "smtp.gmail.com"
  slack:
    enabled: false
    webhook_url: ""
  discord:
    enabled: false
    webhook_url: ""

backup:
  enabled: true
  schedule: "0 2 * * *"
  retention_days: 30
  s3_bucket: "qts-backups"
  s3_region: "us-east-1"
  include_data: true
  include_logs: true

performance:
  max_workers: 4
  worker_timeout: 300
  keep_alive: 2
  max_requests: 1000
  max_requests_jitter: 50

features:
  quantum_neural_networks: true
  temporal_arbitrage: true
  cosmic_intelligence: true
  multiverse_sync: true
  angelic_guidance: true
  divine_timing: true
  sacred_pattern_detection: true
  zero_point_field_analysis: true
  consciousness_validation: true
  reality_enforcement: true
