name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Purge cache and old installs
        run: |
          pip uninstall -y -r requirements.txt || true
          rm -rf ~/.cache/pip
      - name: Install with clean slate
        run: |
          python -m pip install --no-cache-dir --force-reinstall -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest tests/
